baseURL = "https://thehomelab.lol/"
languageCode = "en-us"
title = "TheHomeLab"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowCodeCopyButtons = true
  mainSections = ["docs", "posts"]

  [params.assets]
    favicon = "<link / url to icon>"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/docs/"
    weight = 10
  [[menu.main]]
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.com/@YourChannel"
    weight = 20