baseURL = "https://thehomelab.lol/"
languageCode = "en-us"
title = "TheHomeLab"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowCodeCopyButtons = true
  mainSections = ["blog", "docs"]
  
  # "Edit on GitHub" configuration
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false
  editPost = { URL = "https://github.com/drusho/thehomelab-web/edit/main/content", Text = "Edit this page on GitHub", appendFilePath = true }

  [params.assets]
    favicon = "<link / url to icon>"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 20
  [[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses/"
    weight = 30